# This file contains defaults for the "config" object used in the Snakefile.
# To temporarily override or provide a value, you can use snakemake's --config
# or --configfile options.
---
fasta_path: "/genfs/projects/COVID_consensus/2020_04_27/"
qc_meta: "data/sgil_extract.tsv"
world_meta: "https://raw.githubusercontent.com/nextstrain/ncov/master/data/metadata.tsv"
exclude_latest: "https://raw.githubusercontent.com/nextstrain/ncov/master/config/exclude.txt"


include: "config/include.txt"
reference: "config/reference.gb"
outgroup: "config/outgroup.fasta"
ordering: "config/ordering.tsv"
color_schemes: "config/color_schemes.tsv"
auspice_config: "config/auspice_config.json"
auspice_config_gisaid: "config/auspice_config_gisaid.json"
auspice_config_zh: "config/auspice_config_zh.json"
lat_longs: "config/lat_longs.tsv"
description: "config/description.md"
description_zh: "config/description_zh.md"
clades: "config/clades.tsv"

# filters
group_by: "country year month"
sequences_per_group: "25"
min_length: 27000
exclude_where: "date='2015'"
